<?php

/**
* Implements hook_menu().
*/
function rm_seller_menu() {
    $items = array();
    $items['manage/seller/%user'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_dashboard',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_NORMAL_ITEM,
    );
	$items['manage/seller/%user/dashboard'] = array(
        'title' => 'Dashboard',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0,
    );
    $items['manage/seller/%user/orders'] = array(
        'title' => 'Manage orders',
        'page callback' => 'rm_seller_orders',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 0,
    );
    $items['manage/seller/%user/offers'] = array(
        'title' => 'Manage offers',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_offer_form'),
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
    );
	$items['manage/seller/%user/profile'] = array(
        'title' => 'Manage profile',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_user_editprofile', 2),
        'access callback' => 'rm_user_editprofile_access',
		'access arguments' => array(2),
        'file' => 'rm_user.inc',
        'file path' => drupal_get_path('module', 'rm_user'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
    );
	$items['manage/seller/%user/account'] = array(
        'title' => 'Manage account',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('user_profile_form', 2),
        'access callback' => 'user_edit_access',
        'access arguments' => array(2),
        'file' => 'user.pages.inc',
        'file path' => drupal_get_path('module', 'user'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
    );
	$items['manage/seller/%user/paymentagreements'] = array(
        'title' => 'Manage payment agreements',
        'page callback' => 'rm_seller_paymentagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 4,
    );
	$items['manage/seller/%user/shippingagreements'] = array(
        'title' => 'Manage shipping agreements',
        'page callback' => 'rm_seller_shippingagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
	$items['manage/seller/%user/pickupagreements'] = array(
        'title' => 'Manage pickup agreements',
        'page callback' => 'rm_seller_pickupagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 6,
    );
	$items['manage/seller/%user/commissionagreements'] = array(
        'title' => 'View commission agreements',
        'page callback' => 'rm_seller_commissionagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 6,
    );
    $items['addofferdescription/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_add_offerdescription',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_is_seller',
    );
    $items['addoffervariation/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_add_offervariation',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
    );
    $items['addtradingunit/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_add_tradingunit',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
    );
    $items['changeorderstatus/%/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_cart_change_order_status',
        'page arguments' => array(1, 2),
        'access callback' => 'rm_seller_user_responsible_for_order',
        'access arguments' => array(1),
        'file' => 'rm_cart.module',
        'file path' => drupal_get_path('module', 'rm_cart'),
    );
    $items['pauseoffer/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_pause_offer',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['activateoffer/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_activate_offer',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['manage/seller/deleteoffer/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_delete_offer', 3),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(3),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['manage/seller/deleteagreement/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_agreement_delete', 3),
        'access callback' => 'rm_seller_user_may_edit_agreement',
        'access arguments' => array(3),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['manage/seller/addagreement/%/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_agreement_add', 3, 4),
        'access callback' => 'rm_seller_user_may_add_agreement',
        'access arguments' => array(3, 4),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );  
    $items['manage/seller/editagreement/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_agreement_edit', 3),
        'access callback' => 'rm_seller_user_may_edit_agreement',
        'access arguments' => array(3),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['deleteimage/%/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_delete_image',
        'page arguments' => array(1,2),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
	return $items;
}

function rm_seller_add_tradingunit($nid, $goto = TRUE) {
    $variation = node_load($nid);
	$new_trading_unit = rm_api_create_new_node('trading_unit', node_type_get_name('trading_unit'), 'de', $variation->uid, 0, 0, 0, 0);
    $new_trading_unit->status = 1;
    node_save($new_trading_unit);
    $variation->field_trading_unit_reference[LANGUAGE_NONE][]['target_id'] = $new_trading_unit->nid;
    node_save($variation);
    if($goto) {
        drupal_goto();
    }
    else {
        return array('tu' => $new_trading_unit);
    }
}

function rm_seller_add_offervariation($nid, $goto = TRUE) {
    $offerdescription = node_load($nid);
	$new_trading_unit = rm_api_create_new_node('trading_unit', node_type_get_name('trading_unit'), 'de', $offerdescription->uid, 0, 0, 0, 0);
    $new_trading_unit->status = 1;
    node_save($new_trading_unit);
	$new_offer_variation = rm_api_create_new_node('offer_variation', node_type_get_name('offer_variation'), 'de', $offerdescription->uid, 0, 0, 0, 0);
    $new_offer_variation->status = 1;
    $new_offer_variation->field_trading_unit_reference[LANGUAGE_NONE][]['target_id'] = $new_trading_unit->nid;
    node_save($new_offer_variation);
    $offerdescription->field_offer_variation_reference[LANGUAGE_NONE][]['target_id'] = $new_offer_variation->nid;
    node_save($offerdescription);
    if($goto) {
        drupal_goto();
    }
    else {
        return array('ov' => $new_offer_variation, 'tu' => $new_trading_unit);
    }
}

function rm_seller_add_offerdescription($uid, $goto = TRUE) {
	$new_trading_unit = rm_api_create_new_node('trading_unit', node_type_get_name('trading_unit'), 'de', $uid, 0, 0, 0, 0);
    $new_trading_unit->status = 1;
    node_save($new_trading_unit);
	$new_offer_variation = rm_api_create_new_node('offer_variation', node_type_get_name('offer_variation'), 'de', $uid, 0, 0, 0, 0);
    $new_offer_variation->status = 1;
	$new_offer_description = rm_api_create_new_node('offer_description', node_type_get_name('offer_description'), 'de', $uid, 0, 0, 0, 0);
    $new_offer_variation->field_trading_unit_reference[LANGUAGE_NONE][]['target_id'] = $new_trading_unit->nid;
    node_save($new_offer_variation);
    $new_offer_description->field_offer_variation_reference[LANGUAGE_NONE][]['target_id'] = $new_offer_variation->nid;
    node_save($new_offer_description);
    if($goto) {
        drupal_goto();
    }
    else {
        return array('od' => $new_offer_description, 'ov' => $new_offer_variation, 'tu' => $new_trading_unit);
    }
}

function rm_seller_user_responsible_for_order($order_number) {
    global $user;
    $order_items = rm_cart_get_order($order_number);
    $err = array();
    if(isset($order_items)) {
        foreach($order_items as $order_item) {
            if($order_item->field_user_reference[LANGUAGE_NONE][0]['target_id'] != $user->uid) {
                $err[] = 1;
            }
        }
    }
    else {
        return FALSE;
    }
    if(empty($err)) return TRUE;
}

function rm_seller_user_may_edit_agreement($agreement) {
    if(rm_user_is_admin() || rm_sales_user_is_salesguy()) return TRUE;
    $agreementobject = node_load($agreement);
    global $user;
    if($user->uid == $agreementobject->uid && $agreementobject->type != 'commission_agreement') return TRUE;
}

function rm_seller_user_may_add_agreement($agreement_type, $suid) {
    if(rm_user_is_admin() || rm_sales_user_is_salesguy()) return TRUE;
    global $user;
    if($user->uid == $suid && $agreement_type != 'commission_agreement') return TRUE;
}

function rm_seller_user_is_seller() {
    if(rm_user_is_admin()) return TRUE;
    global $user;
    $account = user_load($user->uid);
    if(in_array('seller', $account->roles)) return TRUE;
}

function rm_seller_user_owns_node($nid) {
    if(rm_user_is_admin()) return TRUE;
    $nodeobject = node_load($nid);
    global $user;
    if($user->uid > 0 && $user->uid == $nodeobject->uid) return TRUE;
}

/**
 * Implements hook_theme().
 */
function rm_seller_theme() {
	return array(
		'rm_seller_offer_form' => array(
			'template' => 'rm_seller_offer_form_theme',
            'arguments' => array('form' => 'form'),
			'render element' => 'form',
		),
		'rm_seller_theme_dashboard' => array(
			'template' => 'rm_seller_dashboard_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),
		'rm_seller_theme_orders' => array(
			'template' => 'rm_seller_orders_theme',
			'variables' => array(
				'vars' => NULL,
			)
		), 
		'rm_seller_theme_paymentagreements' => array(
			'template' => 'rm_seller_paymentagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),    
		'rm_seller_theme_shippingagreements' => array(
			'template' => 'rm_seller_shippingagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),  
		'rm_seller_theme_commissionagreements' => array(
			'template' => 'rm_seller_commissionagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),
		'rm_seller_theme_pickupagreements' => array(
			'template' => 'rm_seller_pickupagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),      
		'user_profile_form' => array(
			'template' => 'user_profile_form_theme',
            'arguments' => array('form' => 'form'),
			'render element' => 'form',
		),
	);
}

function rm_seller_create_shipping_agreement() {

    $query = new EntityFieldQuery();
    $result = $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', array('seller_profile'))
        ->propertyCondition('status', 1)
        ->execute();
        
            
    $sellerprofiles = array();
    if(!empty($result['node'])) {
        $sellerprofiles = entity_load('node', array_keys($result['node']));

        $selleruids = array();
        foreach($sellerprofiles as $sellerprofile) {
            $selleruids[$sellerprofile->uid] = TRUE;
        }

        $query = new EntityFieldQuery();
        $saresult = $query
            ->entityCondition('entity_type', 'node')
            ->entityCondition('bundle', array('shipping_agreement'))
            ->propertyCondition('uid', array_keys($selleruids))
            ->execute();
            
        $shippingagreements = array();
        if(!empty($saresult['node'])) {
            $shippingagreements = entity_load('node', array_keys($saresult['node']));
            
            $shippinguids = array();
            foreach($shippingagreements as $shippingagreement) {
                unset($selleruids[$shippingagreement->uid]);
            }
            
            if(!empty($selleruids)) {
                foreach($selleruids as $suid => $bool) {

                    $field_minimum_order_value[LANGUAGE_NONE][0]['value'] = '100';
                    $field_shipping_zipcodes[LANGUAGE_NONE][0]['value'] = '912';
                    $field_surcharge[LANGUAGE_NONE][0]['value'] = '0';
                    $field_user_reference[LANGUAGE_NONE][0]['target_id'] = '0';
                    
                    $field_regular_times[LANGUAGE_NONE][0]['starthours'] = '0800';
                    $field_regular_times[LANGUAGE_NONE][0]['endhours'] = '1800';
                    $field_regular_times[LANGUAGE_NONE][0]['day'] = 1;
                    $field_regular_times[LANGUAGE_NONE][0]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][1]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][1]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][1]['day'] = 1;
                    // $field_regular_times[LANGUAGE_NONE][1]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][2]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][2]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][2]['day'] = 1;
                    // $field_regular_times[LANGUAGE_NONE][2]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][3]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][3]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][3]['day'] = 1;
                    // $field_regular_times[LANGUAGE_NONE][3]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][4]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][4]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][4]['day'] = 1;
                    // $field_regular_times[LANGUAGE_NONE][4]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][5]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][5]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][5]['day'] = 1;
                    // $field_regular_times[LANGUAGE_NONE][5]['daydelta'] = 5;
                    
                    
                    
                    $field_regular_times[LANGUAGE_NONE][6]['starthours'] = '0800';
                    $field_regular_times[LANGUAGE_NONE][6]['endhours'] = '1800';
                    $field_regular_times[LANGUAGE_NONE][6]['day'] = 2;
                    $field_regular_times[LANGUAGE_NONE][6]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][7]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][7]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][7]['day'] = 2;
                    // $field_regular_times[LANGUAGE_NONE][7]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][8]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][8]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][8]['day'] = 2;
                    // $field_regular_times[LANGUAGE_NONE][8]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][9]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][9]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][9]['day'] = 2;
                    // $field_regular_times[LANGUAGE_NONE][9]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][10]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][10]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][10]['day'] = 2;
                    // $field_regular_times[LANGUAGE_NONE][10]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][11]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][11]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][11]['day'] = 2;
                    // $field_regular_times[LANGUAGE_NONE][11]['daydelta'] = 5;
                    
                    
                    
                    $field_regular_times[LANGUAGE_NONE][12]['starthours'] = '0800';
                    $field_regular_times[LANGUAGE_NONE][12]['endhours'] = '1800';
                    $field_regular_times[LANGUAGE_NONE][12]['day'] = 3;
                    $field_regular_times[LANGUAGE_NONE][12]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][13]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][13]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][13]['day'] = 3;
                    // $field_regular_times[LANGUAGE_NONE][13]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][14]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][14]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][14]['day'] = 3;
                    // $field_regular_times[LANGUAGE_NONE][14]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][15]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][15]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][15]['day'] = 3;
                    // $field_regular_times[LANGUAGE_NONE][15]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][16]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][16]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][16]['day'] = 3;
                    // $field_regular_times[LANGUAGE_NONE][16]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][17]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][17]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][17]['day'] = 3;
                    // $field_regular_times[LANGUAGE_NONE][17]['daydelta'] = 5;
                    
                    
                    
                    $field_regular_times[LANGUAGE_NONE][18]['starthours'] = '0800';
                    $field_regular_times[LANGUAGE_NONE][18]['endhours'] = '1800';
                    $field_regular_times[LANGUAGE_NONE][18]['day'] = 4;
                    $field_regular_times[LANGUAGE_NONE][18]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][19]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][19]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][19]['day'] = 4;
                    // $field_regular_times[LANGUAGE_NONE][19]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][20]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][20]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][20]['day'] = 4;
                    // $field_regular_times[LANGUAGE_NONE][20]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][21]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][21]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][21]['day'] = 4;
                    // $field_regular_times[LANGUAGE_NONE][21]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][22]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][22]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][22]['day'] = 4;
                    // $field_regular_times[LANGUAGE_NONE][22]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][23]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][23]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][23]['day'] = 4;
                    // $field_regular_times[LANGUAGE_NONE][23]['daydelta'] = 5;
                    
                    
                    
                    $field_regular_times[LANGUAGE_NONE][24]['starthours'] = '0800';
                    $field_regular_times[LANGUAGE_NONE][24]['endhours'] = '1800';
                    $field_regular_times[LANGUAGE_NONE][24]['day'] = 5;
                    $field_regular_times[LANGUAGE_NONE][24]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][25]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][25]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][25]['day'] = 5;
                    // $field_regular_times[LANGUAGE_NONE][25]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][26]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][26]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][26]['day'] = 5;
                    // $field_regular_times[LANGUAGE_NONE][26]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][27]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][27]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][27]['day'] = 5;
                    // $field_regular_times[LANGUAGE_NONE][27]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][28]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][28]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][28]['day'] = 5;
                    // $field_regular_times[LANGUAGE_NONE][28]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][29]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][29]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][29]['day'] = 5;
                    // $field_regular_times[LANGUAGE_NONE][29]['daydelta'] = 5;
                    
                    
                    
                    $field_regular_times[LANGUAGE_NONE][30]['starthours'] = '0800';
                    $field_regular_times[LANGUAGE_NONE][30]['endhours'] = '1200';
                    $field_regular_times[LANGUAGE_NONE][30]['day'] = 6;
                    $field_regular_times[LANGUAGE_NONE][30]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][31]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][31]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][31]['day'] = 6;
                    // $field_regular_times[LANGUAGE_NONE][31]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][32]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][32]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][32]['day'] = 6;
                    // $field_regular_times[LANGUAGE_NONE][32]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][33]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][33]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][33]['day'] = 6;
                    // $field_regular_times[LANGUAGE_NONE][33]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][34]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][34]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][34]['day'] = 6;
                    // $field_regular_times[LANGUAGE_NONE][34]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][35]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][35]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][35]['day'] = 6;
                    // $field_regular_times[LANGUAGE_NONE][35]['daydelta'] = 5;
                    
                    
                    
                    // $field_regular_times[LANGUAGE_NONE][36]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][36]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][36]['day'] = 0;
                    // $field_regular_times[LANGUAGE_NONE][36]['daydelta'] = 0;
                    
                    // $field_regular_times[LANGUAGE_NONE][37]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][37]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][37]['day'] = 0;
                    // $field_regular_times[LANGUAGE_NONE][37]['daydelta'] = 1;
                    
                    // $field_regular_times[LANGUAGE_NONE][38]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][38]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][38]['day'] = 0;
                    // $field_regular_times[LANGUAGE_NONE][38]['daydelta'] = 2;
                    
                    // $field_regular_times[LANGUAGE_NONE][39]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][39]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][39]['day'] = 0;
                    // $field_regular_times[LANGUAGE_NONE][39]['daydelta'] = 3;
                    
                    // $field_regular_times[LANGUAGE_NONE][40]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][40]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][40]['day'] = 0;
                    // $field_regular_times[LANGUAGE_NONE][40]['daydelta'] = 4;
                    
                    // $field_regular_times[LANGUAGE_NONE][41]['starthours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][41]['endhours'] = '';
                    // $field_regular_times[LANGUAGE_NONE][41]['day'] = 0;
                    // $field_regular_times[LANGUAGE_NONE][41]['daydelta'] = 5;

                    $title = node_type_get_name('shipping_agreement');
                    $new_node = rm_api_create_new_node('shipping_agreement', $title, 'de', $suid, 1, 0, 0, 0);    
                    
                    $new_node->field_minimum_order_value = $field_minimum_order_value;
                    $new_node->field_shipping_zipcodes = $field_shipping_zipcodes;
                    $new_node->field_surcharge = $field_surcharge;
                    $new_node->field_user_reference = $field_user_reference;
                    $new_node->field_regular_times = $field_regular_times;
                    node_save($new_node);
                }
            }
        }
    }
}