<?php

/**
* Implements hook_menu().
*/
function rm_seller_menu() {
    $items = array();
    $items['manage/seller/%user'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_dashboard',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_NORMAL_ITEM,
    );
	$items['manage/seller/%user/dashboard'] = array(
        'title' => 'Dashboard',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0,
    );
    $items['manage/seller/%user/offers'] = array(
        'title' => 'Manage offers',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_offer_form'),
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
    );
	$items['manage/seller/%user/profile'] = array(
        'title' => 'Manage profile',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_user_editprofile', 2),
        'access callback' => 'rm_user_editprofile_access',
		'access arguments' => array(2),
        'file' => 'rm_user.inc',
        'file path' => drupal_get_path('module', 'rm_user'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
    );
	$items['manage/seller/%user/account'] = array(
        'title' => 'Manage account',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('user_profile_form', 2),
        'access callback' => 'user_edit_access',
        'access arguments' => array(2),
        'file' => 'user.pages.inc',
        'file path' => drupal_get_path('module', 'user'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
    );
	$items['manage/seller/%user/paymentagreements'] = array(
        'title' => 'Manage payment agreements',
        'page callback' => 'rm_seller_paymentagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 4,
    );
	$items['manage/seller/%user/shippingagreements'] = array(
        'title' => 'Manage shipping agreements',
        'page callback' => 'rm_seller_shippingagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
	$items['manage/seller/%user/pickupagreements'] = array(
        'title' => 'Manage pickup agreements',
        'page callback' => 'rm_seller_pickupagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 6,
    );
	$items['manage/seller/%user/commissionagreements'] = array(
        'title' => 'View commission agreements',
        'page callback' => 'rm_seller_commissionagreements',
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 6,
    );
    $items['addofferdescription/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_add_offerdescription',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_is_seller',
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['addoffervariation/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_add_offervariation',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['addtradingunit/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_add_tradingunit',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['pauseoffer/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_pause_offer',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['activateoffer/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_activate_offer',
        'page arguments' => array(1),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['manage/seller/deleteoffer/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_delete_offer', 3),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(3),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['manage/seller/deleteagreement/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_agreement_delete', 3),
        'access callback' => 'rm_seller_user_may_edit_agreement',
        'access arguments' => array(3),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['manage/seller/addagreement/%/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_agreement_add', 3, 4),
        'access callback' => 'rm_seller_user_may_add_agreement',
        'access arguments' => array(3, 4),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );  
    $items['manage/seller/editagreement/%'] = array(
        'title' => 'Seller',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rm_seller_agreement_edit', 3),
        'access callback' => 'rm_seller_user_may_edit_agreement',
        'access arguments' => array(3),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
    $items['deleteimage/%/%'] = array(
        'title' => 'Seller',
        'page callback' => 'rm_seller_delete_image',
        'page arguments' => array(1,2),
        'access callback' => 'rm_seller_user_owns_node',
        'access arguments' => array(1),
        'file' => 'rm_seller.inc',
        'file path' => drupal_get_path('module', 'rm_seller'),
    );
	return $items;
}

function rm_seller_user_may_edit_agreement($agreement) {
    if(rm_user_is_admin() || rm_sales_user_is_salesguy()) return TRUE;
    $agreementobject = node_load($agreement);
    global $user;
    if($user->uid == $agreementobject->uid && $agreementobject->type != 'commission_agreement') return TRUE;
}

function rm_seller_user_may_add_agreement($agreement_type, $suid) {
    if(rm_user_is_admin() || rm_sales_user_is_salesguy()) return TRUE;
    global $user;
    if($user->uid == $suid && $agreement_type != 'commission_agreement') return TRUE;
}

function rm_seller_user_is_seller() {
    if(rm_user_is_admin()) return TRUE;
    global $user;
    $account = user_load($user->uid);
    if(in_array('seller', $account->roles)) return TRUE;
}

function rm_seller_user_owns_node($nid) {
    if(rm_user_is_admin()) return TRUE;
    $nodeobject = node_load($nid);
    global $user;
    if($user->uid > 0 && $user->uid == $nodeobject->uid) return TRUE;
}

/**
 * Implements hook_theme().
 */
function rm_seller_theme() {
	return array(
		'rm_seller_offer_form' => array(
			'template' => 'rm_seller_offer_form_theme',
            'arguments' => array('form' => 'form'),
			'render element' => 'form',
		),
		'rm_seller_theme_dashboard' => array(
			'template' => 'rm_seller_dashboard_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),
		'rm_seller_theme_paymentagreements' => array(
			'template' => 'rm_seller_paymentagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),    
		'rm_seller_theme_shippingagreements' => array(
			'template' => 'rm_seller_shippingagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),  
		'rm_seller_theme_commissionagreements' => array(
			'template' => 'rm_seller_commissionagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),
		'rm_seller_theme_pickupagreements' => array(
			'template' => 'rm_seller_pickupagreements_theme',
			'variables' => array(
				'vars' => NULL,
			)
		),      
		'user_profile_form' => array(
			'template' => 'user_profile_form_theme',
            'arguments' => array('form' => 'form'),
			'render element' => 'form',
		),
	);
}